Repository dooboolab-community/dooboo-ui, pull requests merged in 2021-09, with the labels that each got.

#92 Replace hyperlink in getting started documentation
  docs/src/overview/readme.stories.mdx
Labels: 📖 documentation

#91 Add CustomLoadingIndicator in demo
  stories/Icon.tsx
  stories/dooboo-ui/LoadingIndicatorStories/CustomLoadingIndicator.tsx
  stories/dooboo-ui/LoadingIndicatorStories/index.tsx
Labels: :notebook_with_decorative_cover: demo, :thinking: possibility

#90 Update documentation for [Checkbox]
  docs/src/components/Checkbox/Basic.tsx
  docs/src/components/Checkbox/Checkbox.stories.mdx
  docs/src/components/Checkbox/Disabled.tsx
  docs/src/components/Checkbox/LeftElement.tsx
  docs/src/components/Checkbox/RightElement.tsx
  docs/src/components/Checkbox/Solid.tsx
  docs/src/components/Checkbox/index.tsx
Labels: 📖 documentation

#99 Add 16 more dooboo-ui icons v1.0.3
  CHANGELOGS.md
  docs/src/assets/doobooui.ttf
  docs/src/components/Icon/Default.tsx
  docs/src/contributing/contributing.stories.mdx
  lib/package.json
  main/Icon/doobooui.ttf
  main/Icon/index.tsx
  main/Icon/selection.json
  stories/dooboo-ui/IconStories/IconStory.tsx
Labels: 🍗 enhancement, :small_blue_diamond: assets

#73 Implement a select box
  docs/package.json
  docs/src/components/SelectBox/SelectBox.stories.mdx
  docs/src/components/SelectBox/index.tsx
  docs/yarn.lock
  jest.config.js
  lib/package.json
  main/SelectBox/index.tsx
  main/__tests__/SelectBox.test.tsx
  main/__tests__/__snapshots__/SelectBox.test.tsx.snap
  main/index.ts
  package.json
  stories/dooboo-ui/SelectBoxStories/SelectBoxStory.tsx
  stories/dooboo-ui/SelectBoxStories/index.tsx
  stories/index.ts
  test/jestSetup.ts
  yarn.lock
Labels: 🎯 feature

#100 Delete unused file
  docs/src/components/ButtonGroup/SignInPage.tsx
Labels: 🥢 typo

#101 Support Expo Snack for [Button] sample code
  docs/src/components/Button/Button.stories.mdx
  docs/src/components/Button/Link.tsx
  docs/src/components/Button/index.tsx
Labels: 🍗 enhancement

#102 Import React in SwitchToggle
  main/SwitchToggle.tsx
Labels: 🍗 enhancement, 🔥 hotfix

#105 Enhance useTheme to provide default theme without ThemeProvider
  main/SwitchToggle.tsx
  main/theme/ThemeProvider.tsx
  main/theme/createCtx.tsx
Labels: 🍗 enhancement, :construction_worker_man: refactor

#106 Remove unnecessary suffix in [SwitchToggle] variables
  docs/src/components/SwitchToggle/SwitchToggle.stories.mdx
  main/SwitchToggle.tsx
  main/__tests__/SwitchToggle.test.tsx
  stories/dooboo-ui/SwitchToggleStories/SwitchToggleDefaultStory.tsx
Labels: 🍗 enhancement

#109 Update documentation for [IconButton]
  docs/src/components/IconButton/IconButton.stories.mdx
  docs/src/components/IconButton/index.tsx
Labels: 📖 documentation

#111 Update documentation for [LoadingIndicator]
  docs/src/components/LoadingIndicator/Basic.tsx
  docs/src/components/LoadingIndicator/ImageVersion.tsx
  docs/src/components/LoadingIndicator/LoadingIndicator.stories.mdx
  docs/src/components/LoadingIndicator/index.tsx
  docs/src/icon.ts
Labels: 📖 documentation

#112 Enhance NetworkImage
  main/NetworkImage.tsx
  stories/dooboo-ui/NetworkImageStories/index.tsx
Labels: 🍗 enhancement

#87 Implement AlertDialog (#71)
  packages/AlertDialog/README.md
  packages/AlertDialog/index.tsx
  packages/AlertDialog/package.json
  packages/AlertDialog/tsconfig.json
  stories/index.ts
  stories/packages/AlertDialogStories/index.tsx
  yarn.lock
Labels: 🎯 feature

#116 Update PR template with yarn test:all
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 💨 ci, 🏗 workflow

#115 Replace source prop with uri prop in [NetworkImage]
  main/NetworkImage.tsx
  stories/dooboo-ui/NetworkImageStories/index.tsx
Labels: 🍗 enhancement

#67 [Implement] : FAB
  main/FAB/index.tsx
  main/IconButton/index.tsx
  main/__tests__/FAB.test.tsx
  main/index.ts
  stories/dooboo-ui/FloatingActionButton/FABStory.tsx
  stories/dooboo-ui/FloatingActionButton/index.tsx
  stories/index.ts
Labels: 🎯 feature

#119 Remove nested component declaration in [AlertDialog]
  packages/AlertDialog/index.tsx
Labels: 🍗 enhancement

#121 Remove unnecessary properties in Theme declaration
  docs/src/styled.d.ts
  main/theme/styled.d.ts
Labels: ❄️ types, 🍗 enhancement

#123 Rewrite NetworkImage
  main/NetworkImage.tsx
  stories/dooboo-ui/NetworkImageStories/index.tsx
Labels: 🍗 enhancement, :construction_worker_man: refactor

#124 hotfix: Fix layout styles in [NetworkImage]
  main/NetworkImage.tsx
  stories/dooboo-ui/NetworkImageStories/index.tsx
Labels: 🍗 enhancement, 🔥 hotfix

#129 Add dooboo-ui/theme
  package.json
  packages/Theme/README.md
  packages/Theme/ThemeProvider.test.tsx
  packages/Theme/Themeprovider.tsx
  packages/Theme/colors.ts
  packages/Theme/createDoobooContext.test.tsx
  packages/Theme/createDoobooContext.tsx
  packages/Theme/index.tsx
  packages/Theme/package.json
  packages/Theme/styled.d.ts
  packages/Theme/tsconfig.json
  packages/Theme/useColorScheme.ts
  yarn.lock
Labels: 🎯 feature, :construction_worker_man: refactor

#132 Enhance CI script
  .github/workflows/ci.yml
Labels: 💨 ci, 🍗 enhancement
