Repository dooboolab-community/dooboo-ui, pull requests merged in 2021-06, with the labels that each got.

#9 Organize colors and theme
  CHANGELOGS.md
  README.md
  lib/package.json
  main/Button.tsx
  main/EditText.tsx
  main/__tests__/Accordion.test.tsx
  main/theme/ThemeProvider.tsx
  main/theme/colors.ts
  main/theme/index.ts
  packages/CalendarCarousel/index.tsx
  packages/GiftedChat/README.md
  packages/GiftedChat/index.tsx
  stories/dooboo-ui/ButtonStories/ButtonDefaultStory.tsx
  stories/dooboo-ui/ButtonStories/index.tsx
  stories/dooboo-ui/EditTextStories/EditTextColumnStory.tsx
  stories/dooboo-ui/EditTextStories/EditTextRowStory.tsx
  stories/dooboo-ui/EditTextStories/index.tsx
  stories/dooboo-ui/TypographyStories/index.tsx
  tsconfig.json
Labels: 🍗 enhancement

#10 [Bugfix] Fix theme change listener not triggering
  main/theme/ThemeProvider.tsx
  main/theme/colors.ts
  main/theme/useColorScheme.tsx
Labels: 🛠 bugfix

#11 Redesign button component
  jest.config.js
  main/Button/index.tsx
  main/StatusBarBrightness.tsx
  main/Typography/Typography.tsx
  main/Typography/TypographyInverted.tsx
  main/Typography/index.tsx
  main/__tests__/Accordion.test.tsx
  main/__tests__/Button.test.tsx
  main/__tests__/ButtonGroup.test.tsx
  main/__tests__/EditText.test.tsx
  main/__tests__/LoadingIndicator.test.tsx
  main/__tests__/__snapshots__/EditText.test.tsx.snap
  main/theme/ThemeProvider.tsx
  main/theme/colors.ts
  main/theme/useColorScheme.tsx
  package.json
  stories/dooboo-ui/ButtonStories/ButtonDefaultStory.tsx
  stories/dooboo-ui/ButtonStories/index.tsx
  stories/dooboo-ui/EditTextStories/index.tsx
  stories/dooboo-ui/LoadingIndicatorStories/index.tsx
  stories/dooboo-ui/TypographyStories/index.tsx
  test/setupTest.ts
  test/testUtils.tsx
Labels: 🎯 feature, 🚽 migration

#12 Minor fixes in [Button] in colors
  lib/package.json
  main/Button/index.tsx
  main/__tests__/Button.test.tsx
  stories/dooboo-ui/ButtonStories/ButtonDefaultStory.tsx
Labels: 🍗 enhancement, 🧪 test

#13 Fix `disabled` button style for both themes
  lib/package.json
  main/Button/index.tsx
  stories/dooboo-ui/ButtonStories/ButtonDefaultStory.tsx
  stories/dooboo-ui/ButtonStories/index.tsx
Labels: 🍗 enhancement, 🛠 bugfix

#14 Update [EditText-column] to fit the design
  README.md
  main/EditText.tsx
  main/Hr.tsx
  main/__tests__/EditText.test.tsx
  main/__tests__/__snapshots__/EditText.test.tsx.snap
  main/index.ts
  stories/dooboo-ui/ButtonStories/ButtonDefaultStory.tsx
  stories/dooboo-ui/EditTextStories/EditTextColumnStory.tsx
  stories/dooboo-ui/EditTextStories/EditTextRowStory.tsx
  stories/dooboo-ui/EditTextStories/EditTextWithThemeStory.tsx
  stories/dooboo-ui/EditTextStories/index.tsx
Labels: 🍗 enhancement, 🎯 feature

#16 [Enhancement] EditText stories and web effect
  main/EditText.tsx
  stories/dooboo-ui/EditTextStories/EditTextBoxedStory.tsx
  stories/dooboo-ui/EditTextStories/EditTextColumnStory.tsx
  stories/dooboo-ui/EditTextStories/EditTextRowStory.tsx
Labels: 🍗 enhancement

#17 Prevent [Button] from `press` when loading
  main/Button/index.tsx
  stories/dooboo-ui/EditTextStories/EditTextBoxedStory.tsx
Labels: 🍗 enhancement, 🔥 hotfix

#18 Integrate custom font icons to package
  README.md
  jest.config.js
  lib/package.json
  main/Icon/doobooui.ttf
  main/Icon/index.tsx
  main/Icon/selection.json
  main/__tests__/Icon.test.tsx
  main/index.ts
  package.json
  stories/dooboo-ui/IconStories/IconStory.tsx
  stories/dooboo-ui/IconStories/index.tsx
  stories/index.ts
  yarn.lock
Labels: 🎯 feature

#21 Initial proposal for [Checkbox]
  lib/package.json
  main/Checkbox/index.tsx
  main/LoadingIndicator.tsx
  main/__tests__/Checkbox.test.tsx
  main/__tests__/IconButton.test.tsx
  main/__tests__/__snapshots__/LoadingIndicator.test.tsx.snap
  main/index.ts
  stories/dooboo-ui/CheckboxStories/CheckboxStory.tsx
  stories/dooboo-ui/CheckboxStories/index.tsx
  stories/dooboo-ui/IconButtonStories/IconButtonStory.tsx
  stories/index.ts
Labels: 🎯 feature, 🏃🏻‍♀️ in progress

#22 Correctly render component stories
  main/Button/index.tsx
  main/ButtonGroup.tsx
  main/Checkbox/index.tsx
  main/__tests__/ButtonGroup.test.tsx
  main/__tests__/__snapshots__/ButtonGroup.test.tsx.snap
  stories/dooboo-ui/ButtonGroupStories/index.tsx
  stories/dooboo-ui/ButtonStories/ButtonDefaultStory.tsx
  stories/dooboo-ui/CheckboxStories/CheckboxStory.tsx
  stories/dooboo-ui/IconButtonStories/IconButtonStory.tsx
  stories/dooboo-ui/IconButtonStories/index.tsx
  stories/dooboo-ui/IconStories/IconStory.tsx
  test/setupTest.ts
Labels: 🍗 enhancement

#23 Refactor [Button] styled-component to reuse complicating color system
  jest.config.js
  main/Button/index.tsx
  main/Checkbox/index.tsx
  main/IconButton/index.tsx
  main/Styled/StyledComponents.tsx
  main/__tests__/Button.test.tsx
  stories/dooboo-ui/ButtonStories/ButtonDefaultStory.tsx
Labels: :construction_worker_man: refactor

#24 Refactor [LoadingIndicator]
  main/LoadingIndicator.tsx
  main/StatusBarBrightness.tsx
  main/__tests__/Hr.test.tsx
  main/__tests__/LoadingIndicator.test.tsx
  main/__tests__/StatusBarBrightness.test.tsx
  main/__tests__/__snapshots__/LoadingIndicator.test.tsx.snap
  stories/dooboo-ui/LoadingIndicatorStories/index.tsx
Labels: :construction_worker_man: refactor, 🍗 enhancement

#26 Add [RadioGroup] to main component
  main/RadioGroup/RadioButton.tsx
  main/RadioGroup/index.tsx
  main/Styled/StyledComponents.tsx
  main/SwitchToggle.tsx
  main/Typography/Typography.tsx
  main/Typography/TypographyInverted.tsx
  main/__tests__/RadioGroup.test.tsx
  main/__tests__/SwitchToggle.test.tsx
  main/__tests__/Typography.test.tsx
  main/__tests__/__snapshots__/RadioGroup.test.tsx.snap
  main/__tests__/__snapshots__/SwitchToggle.test.tsx.snap
  main/index.ts
  stories/dooboo-ui/ButtonStories/ButtonDefaultStory.tsx
  stories/dooboo-ui/CheckboxStories/CheckboxStory.tsx
  stories/dooboo-ui/IconButtonStories/IconButtonStory.tsx
  stories/dooboo-ui/RadioGroupStories/RadioGroupStory.tsx
  stories/dooboo-ui/RadioGroupStories/index.tsx
  stories/index.ts
Labels: 🎯 feature

#27 Add animation to [Checkbox] and [RadioButton]
  lib/package.json
  main/Checkbox/index.tsx
  main/RadioGroup/RadioButton.tsx
  main/Styled/StyledComponents.tsx
  main/__tests__/Checkbox.test.tsx
  main/__tests__/RadioGroup.test.tsx
  main/__tests__/__snapshots__/RadioGroup.test.tsx.snap
  stories/dooboo-ui/RadioGroupStories/RadioGroupStory.tsx
Labels: 🍗 enhancement, 📘 release

#29 Update colors to updated design
  README_THEME.md
  main/Checkbox/index.tsx
  main/RadioGroup/RadioButton.tsx
  main/Styled/StyledComponents.tsx
  main/__tests__/Button.test.tsx
  main/__tests__/Checkbox.test.tsx
  main/__tests__/RadioGroup.test.tsx
  main/__tests__/__snapshots__/RadioGroup.test.tsx.snap
  main/theme/colors.ts
  stories/dooboo-ui/ButtonStories/ButtonDefaultStory.tsx
  stories/dooboo-ui/CheckboxStories/CheckboxStory.tsx
  stories/dooboo-ui/RadioGroupStories/RadioGroupStory.tsx
Labels: :construction_worker_man: refactor, 🍗 enhancement

#30 Add [NetworkImage] to main component
  main/NetworkImage.tsx
  main/__assets__/artifacts_logo_d.png
  main/__assets__/artifacts_logo_d@2x.png
  main/__assets__/artifacts_logo_d@3x.png
  main/__assets__/artifacts_logo_l.png
  main/__assets__/artifacts_logo_l@2x.png
  main/__assets__/artifacts_logo_l@3x.png
  main/__assets__/check.png
  main/__assets__/check_tick.png
  main/__assets__/checkbox-mark.png
  main/__assets__/mark.png
  main/__assets__/star_d.png
  main/__assets__/star_s.png
  main/index.ts
  stories/Icon.tsx
  stories/dooboo-ui/NetworkImageStories/index.tsx
  stories/index.ts
Labels: 🎯 feature

#32 Provide easier font installation for rn-cli
  CHANGELOGS.md
  README.md
  lib/package.json
  main/Icon/index.tsx
  main/react-native.config.js
  package.json
  tsconfig.json
Labels: 🍗 enhancement

#31 Storybook advanced
  docs/.storybook/main.js
  docs/.storybook/manager-head.html
  docs/.storybook/manager.js
  docs/.storybook/preview.js
  docs/.storybook/webpack.config.js
  docs/babel.config.js
  docs/environment.d.ts
  docs/package.json
  docs/src/assets/arrow_down.png
  docs/src/assets/doobooui.ttf
  docs/src/assets/facebook.png
  docs/src/assets/facebook@2x.png
  docs/src/assets/facebook@3x.png
  docs/src/assets/google.png
  docs/src/assets/google@2x.png
  docs/src/assets/google@3x.png
  docs/src/assets/icon.ico
  docs/src/assets/icon.png
  docs/src/components/Accordion/Accordion.stories.mdx
  docs/src/components/Accordion/index.tsx
  docs/src/components/Button/Button.stories.mdx
  docs/src/components/Button/index.tsx
  docs/src/components/ButtonGroup/ButtonGroup.stories.mdx
  docs/src/components/ButtonGroup/index.tsx
  docs/src/components/Checkbox/Checkbox.stories.mdx
  docs/src/components/Checkbox/index.tsx
  docs/src/icon.ts
  docs/src/introduce.stories.mdx
  docs/src/styled.d.ts
  docs/tsconfig.json
  docs/yarn.lock
Labels: 📖 documentation

#33 Setup workflow on deploy docs hosting
  .github/workflows/deploy-docs-staging.yml
  .github/workflows/deploy-docs.yml
  .gitignore
  README.md
  docs/.firebaserc
  docs/.gitignore
  docs/firebase.json
  docs/package.json
  docs/src/components/Button/AdditionalElement.tsx
  docs/src/components/Button/Basic.tsx
  docs/src/components/Button/Button.stories.mdx
  docs/src/components/Button/Outlined.tsx
  docs/src/components/Button/Sizes.tsx
  docs/src/components/Button/index.tsx
  docs/src/components/Checkbox/Checkbox.stories.mdx
  docs/src/components/Checkbox/Default.tsx
  docs/src/components/Checkbox/LeftElement.tsx
  docs/src/components/Checkbox/RightElement.tsx
  docs/src/components/Checkbox/index.tsx
  docs/src/introduce.stories.mdx
  docs/yarn.lock
Labels: 📖 documentation

#34 Reorganize docs and small enhancement on [Accordion]
  CHANGELOGS.md
  CONTRIBUTING.md
  README.md
  docs/package.json
  docs/src/components/Accordion/index.tsx
  docs/src/components/Icon/Default.tsx
  docs/src/components/Icon/Icon.stories.mdx
  docs/src/components/Icon/index.tsx
  docs/src/readme.stories.mdx
  docs/src/theming.stories.mdx
  docs/yarn.lock
  lib/package.json
  main/Accordion/AccordionItem.tsx
  main/Icon/index.tsx
  main/__tests__/__snapshots__/Accordion.test.tsx.snap
  stories/dooboo-ui/AccordionStories/stories.tsx
Labels: 🍗 enhancement
