Repository dooboolab-community/dooboo-ui, pull requests merged in 2021-10, with the labels that each got.

#136 [fix] Change Gap between the FAB buttons.
  main/FAB/index.tsx
Labels: 🍗 enhancement

#138 feat: Add global fontFamily
  CHANGELOGS.md
  lib/package.json
  main/Typography/index.tsx
Labels: 🎯 feature

#137 Support Expo Snack for [LoadingIndicator] sample code
  docs/src/components/LoadingIndicator/LoadingIndicator.stories.mdx
  docs/src/components/LoadingIndicator/index.tsx
Labels: 📖 documentation

#141 [Document] Wrote a document for FAB.
  docs/src/components/FAB/FAB.stories.mdx
  docs/src/components/FAB/index.tsx
Labels: 📖 documentation

#152 Refactor theme package
  docs/src/components/Button/Button.stories.mdx
  docs/src/components/ButtonGroup/ButtonGroup.stories.mdx
  docs/src/components/Checkbox/Checkbox.stories.mdx
  docs/src/components/LoadingIndicator/LoadingIndicator.stories.mdx
  docs/src/components/SelectBox/SelectBox.stories.mdx
  main/Button/index.tsx
  main/Button/stories/DefaultStory.tsx
  main/Checkbox/stories/DefaultStory.tsx
  main/NetworkImage/stories/DefaultStory.tsx
  main/Styled/StyledComponents.tsx
  package.json
  packages/AlertDialog/package.json
  packages/CalendarCarousel/package.json
  packages/GiftedChat/package.json
  packages/PinchZoom/package.json
  packages/theme/README.md
  packages/theme/ThemeProvider.test.tsx
  packages/theme/Themeprovider.tsx
  packages/theme/colors.ts
  packages/theme/createDoobooContext.test.tsx
  packages/theme/createDoobooContext.tsx
  packages/theme/index.tsx
  packages/theme/package.json
  packages/theme/styled.d.ts
  packages/theme/tsconfig.json
  packages/theme/useColorScheme.ts
  yarn.lock
Labels: :construction_worker_man: refactor

#153 Apply new theme package to AlertDialog
  lerna.json
  package.json
  packages/AlertDialog/.npmignore
  packages/AlertDialog/index.tsx
  packages/AlertDialog/packages.json
  packages/AlertDialog/stories/index.tsx
  packages/CalendarCarousel/.npmignore
  packages/CalendarCarousel/package.json
  packages/GiftedChat/.npmignore
  packages/GiftedChat/package.json
  packages/PinchZoom/.npmignore
  packages/PinchZoom/package.json
  packages/theme/README.md
  packages/theme/Themeprovider.tsx
  packages/theme/package.json
  packages/theme/styled.d.ts
  yarn.lock
Labels: 🚽 migration

#156 Fix [Button] loading color
  CHANGELOGS.md
  lib/package.json
  main/Button/index.tsx
  main/Button/stories/DefaultStory.tsx
  main/Snackbar/stories/DefaultStory.tsx
  main/Styled/StyledComponents.tsx
  packages/CalendarCarousel/index.tsx
Labels: 🛠 bugfix, 🍗 enhancement
