Repository dooboolab-community/dooboo-ui, pull requests merged in 2021-08, with the labels that each got.

#43 Fix typo in [Accordion] test
  main/__tests__/Accordion.test.tsx
  main/__tests__/__snapshots__/Accordion.test.tsx.snap
Labels: 🥢 typo

#44 Fix inappropriate word in docs
  docs/src/overview/readme.stories.mdx
  packages/CalendarCarousel/README.md
Labels: 📖 documentation

#46 Remove chained ternaries in StyledComponents
  main/Styled/StyledComponents.tsx
Labels: :construction_worker_man: refactor

#47 Update packages
  package.json
  test/setupTest.ts
  yarn.lock
Labels: :package: update packages

#48 Remove duplicates in [CheckboxStory]
  main/Checkbox/index.tsx
  package.json
  stories/dooboo-ui/CheckboxStories/CheckboxStory.tsx
Labels: 📖 documentation, 🍗 enhancement

#51 Add dooboo-ui package stategy description
  docs/src/overview/readme.stories.mdx
Labels: 📖 documentation

#50 Add label and disabled form for each checkbox type
  stories/dooboo-ui/CheckboxStories/CheckboxStory.tsx
Labels: 📖 documentation, :construction_worker_man: refactor

#53 Rewrite [ButtonGroup] test
  main/__tests__/ButtonGroup.test.tsx
  main/__tests__/__snapshots__/ButtonGroup.test.tsx.snap
  package.json
  test/setupTest.ts
  yarn.lock
Labels: 🧪 test, :construction_worker_man: refactor

#56 Remove responsibility for managing state from [ButtonGroup]
  docs/src/components/ButtonGroup/ButtonGroup.stories.mdx
  docs/src/components/ButtonGroup/index.tsx
  main/ButtonGroup.tsx
  main/__tests__/ButtonGroup.test.tsx
  package.json
  stories/dooboo-ui/ButtonGroupStories/index.tsx
  test/setupTest.ts
  yarn.lock
Labels: 🍗 enhancement, 🧪 test

#61 fix: [CheckboxStory] responsive layout
  stories/dooboo-ui/CheckboxStories/CheckboxStory.tsx
Labels: 📖 documentation, 🍗 enhancement

#62 Fix borderRadius-related bug in [ButtonGroup]
  main/ButtonGroup.tsx
  main/__tests__/ButtonGroup.test.tsx
  main/__tests__/__snapshots__/ButtonGroup.test.tsx.snap
  package.json
  test/setupTest.ts
  yarn.lock
Labels: 🍗 enhancement

#64 Fix ButtonGroup component storybook docs rendering error
  docs/babel.config.js
  docs/package.json
  docs/yarn.lock
Labels: 🛠 bugfix, 🍗 enhancement

#66 Refactor AccordionItem
  main/Accordion/AccordionItem.tsx
Labels: :construction_worker_man: refactor

#68 Detect orientation on media query
  docs/src/styled.d.ts
  main/theme/ThemeProvider.tsx
  main/theme/colors.ts
  main/theme/styled.d.ts
Labels: 🍗 enhancement

#72 Provide unique ID for each item in [CheckboxStory]
  stories/dooboo-ui/CheckboxStories/CheckboxStory.tsx
Labels: 📖 documentation

#69 Replace style props to styles in [Accordion]
  docs/src/components/Accordion/Accordion.stories.mdx
  main/Accordion/AccordionItem.tsx
  main/Accordion/index.tsx
  main/__tests__/__snapshots__/Accordion.test.tsx.snap
  stories/dooboo-ui/AccordionStories/stories.tsx
Labels: :construction_worker_man: refactor

#75 Add display maxLength to EditText
  main/EditText.tsx
  main/__tests__/EditText.test.tsx
  main/__tests__/__snapshots__/EditText.test.tsx.snap
  stories/dooboo-ui/EditTextStories/EditTextColumnStory.tsx
Labels: 🍗 enhancement

#77 Fix style error of newly added EditText maxLength
  main/EditText.tsx
Labels: 🛠 bugfix, 🍗 enhancement

#84 Update documentation for [Accordion]
  docs/src/components/Accordion/Accordion.stories.mdx
Labels: 📖 documentation

#79 Env: update peer dependencies
  lib/package.json
Labels: dependencies

#89 Redesign docs and provide detailed readme on contributing
  .github/PULL_REQUEST_TEMPLATE.md
  docs/.storybook/manager-head.html
  docs/.storybook/manager.js
  docs/.storybook/preview.js
  docs/.storybook/theme.js
  docs/package.json
  docs/src/contributing/contributing.stories.mdx
  docs/src/overview/readme.stories.mdx
  docs/yarn.lock
  package.json
  stories/dooboo-ui/RadioGroupStories/RadioGroupStory.tsx
  yarn.lock
Labels: 📖 documentation, :package: update packages

#88 Update documentatin for [RadioGroup]
  docs/src/components/RadioGroup/Default.tsx
  docs/src/components/RadioGroup/RadioGroup.stories.mdx
  docs/src/components/RadioGroup/WithLabels.tsx
  docs/src/components/RadioGroup/index.tsx
  main/RadioGroup/index.tsx
Labels: 📖 documentation
