Repository dooboolab-community/dooboo-ui, pull requests merged in 2022-01, with the labels that each got.

#176 fix: borderLeftWidth for LastElement button
  main/ButtonGroup/index.tsx
  main/__tests__/ButtonGroup.test.tsx
Labels: ButtonGroup, 🎨 style

#179 Update docs of Accordion
  docs/src/components/Accordion/Accordion.stories.mdx
Labels: 📖 documentation

#181 Add more icons
  CHANGELOGS.md
  docs/src/assets/doobooui.ttf
  docs/src/components/Icon/Default.tsx
  lib/package.json
  main/Icon/doobooui.ttf
  main/Icon/index.tsx
  main/Icon/selection.json
  main/__tests__/__snapshots__/Accordion.test.tsx.snap
Labels: 📘 release, 🍗 enhancement
