Repository dooboolab-community/dooboo-ui, pull requests merged in 2023-02, with the labels that each got.

#228 feature: renew ButtonGroup
  main/__tests__/Button.test.tsx
  main/__tests__/ButtonGroup.test.tsx
  main/components/Button/index.tsx
  main/components/ButtonGroup/__tests__/ButtonGroup.test.tsx
  main/components/ButtonGroup/index.tsx
  main/components/ButtonGroup/stories/DefaultStory.tsx
  main/components/ButtonGroup/stories/basic.tsx
  main/components/ButtonGroup/stories/components/CustomButton.tsx
  main/components/ButtonGroup/stories/components/CustomData.tsx
  main/components/ButtonGroup/stories/components/SingleSelect.tsx
  main/components/ButtonGroup/stories/components/Vertical.tsx
  main/components/ButtonGroup/stories/index.tsx
Labels: 🎯 feature

#231 refactor: [Button] component and organize stories
  .vscode/settings.json
  commitlint.config.cjs
  docs/src/components/ButtonGroup/index.tsx
  docs/src/contributing/contributing.stories.mdx
  main/__tests__/Button.test.tsx
  main/components/Button/index.tsx
  main/components/Button/stories/DefaultStory.tsx
  main/components/Button/stories/basic/Basic.tsx
  main/components/Button/stories/basic/Color/OutlinedButtonColors.tsx
  main/components/Button/stories/basic/Color/SolidButtonColors.tsx
  main/components/Button/stories/basic/Color/TextButtonColors.tsx
  main/components/Button/stories/basic/Color/index.tsx
  main/components/Button/stories/basic/Custom.tsx
  main/components/Button/stories/basic/Disabled.tsx
  main/components/Button/stories/basic/Event/Counter.tsx
  main/components/Button/stories/basic/Event/GoogleSignIn.tsx
  main/components/Button/stories/basic/Event/index.tsx
  main/components/Button/stories/basic/Loading/LoadingElement.tsx
  main/components/Button/stories/basic/Loading/index.tsx
  main/components/Button/stories/basic/Sizes.tsx
  main/components/Button/stories/basic/StartAndEnd.tsx
  main/components/Button/stories/basic/index.tsx
  main/components/Button/stories/components/index.tsx
  test/testUtils.tsx
Labels: 🎯 feature, preview

#232 feat: dooboo provider
  .storybook/index.ts
  docs/src/components/Accordion/index.tsx
  docs/src/overview/readme.stories.mdx
  docs/src/overview/theming.stories.mdx
  main/components/Button/index.tsx
  main/components/Snackbar/index.tsx
  main/components/Snackbar/stories/ActionStory.tsx
  main/components/Snackbar/stories/DefaultStory.tsx
  main/components/Snackbar/stories/index.tsx
  main/index.ts
  main/modals/AlertDialog/index.tsx
  main/modals/AlertDialog/stories/BasicStory.tsx
  main/modals/AlertDialog/stories/index.tsx
  main/modals/Snackbar/index.tsx
  main/modals/Snackbar/stories/BasicStory.tsx
  main/modals/Snackbar/stories/index.tsx
  main/providers/index.tsx
  packages/AlertDialog/.npmignore
  packages/AlertDialog/README.md
  packages/AlertDialog/index.tsx
  packages/AlertDialog/packages.json
  packages/AlertDialog/stories/DefaultStory.tsx
  packages/AlertDialog/stories/index.tsx
  packages/AlertDialog/tsconfig.json
  packages/theme/ThemeProvider.tsx
Labels: 📖 documentation, 🎯 feature, :construction_worker_man: refactor, preview

#233 feat: impl minimal [AlertDialog] with actions
  main/components/Button/index.tsx
  main/modals/AlertDialog/index.tsx
  main/modals/AlertDialog/stories/BasicStory.tsx
  main/modals/AlertDialog/stories/index.tsx
  main/modals/Snackbar/stories/index.tsx
  packages/CalendarCarousel/stories/index.tsx
  packages/PinchZoom/stories/index.tsx
Labels: 🎯 feature, preview

#234 refactor: renew [Snackbar] component with simpler impl
  main/modals/AlertDialog/index.tsx
  main/modals/Snackbar/const.ts
  main/modals/Snackbar/index.tsx
  main/modals/Snackbar/stories/BasicStory.tsx
  main/providers/index.tsx
Labels: :construction_worker_man: refactor

#240 feat: icons v0.2
  docs/lib/tsconfig.tsbuildinfo
  docs/src/assets/doobooui.ttf
  docs/src/components/Accordion/Accordion.stories.mdx
  docs/src/components/Accordion/ExRenderFunction.tsx
  docs/src/components/FAB/index.tsx
  docs/src/components/Icon/Default.tsx
  docs/src/components/Icon/Icon.stories.mdx
  docs/src/components/IconButton/index.tsx
  main/modals/AlertDialog/index.tsx
  main/modals/Snackbar/index.tsx
  main/uis/Accordion/AccordionItem.tsx
  main/uis/Checkbox/index.tsx
  main/uis/FAB/index.tsx
  main/uis/Icon/__tests__/Icon.test.tsx
  main/uis/Icon/doobooui.ttf
  main/uis/Icon/index.tsx
  main/uis/Icon/selection.json
  main/uis/IconButton/index.tsx
  stories/uis/AccordionStories/AccordionCustomStory.tsx
  stories/uis/ButtonGroupStories/common/CustomData.tsx
  stories/uis/ButtonStories/ButtonStartAndEndStory.tsx
  stories/uis/FABStories/FABBasicStory.tsx
  stories/uis/IconButtonStories/IconButtonBasicStory.tsx
  stories/uis/IconButtonStories/IconButtonColorStory.tsx
  stories/uis/IconButtonStories/IconButtonDisabledStory.tsx
  stories/uis/IconButtonStories/IconButtonIconElementStory.tsx
  stories/uis/IconButtonStories/IconButtonSizeStory.tsx
  stories/uis/IconStories/IconBasicStory.tsx
Labels: 🎯 feature

#241 refactor: ButtonGroup data type
  .vscode/settings.json
  docs/src/components/Accordion/Accordion.stories.mdx
  main/modals/AlertDialog/index.tsx
  main/uis/Accordion/AccordionItem.tsx
  main/uis/ButtonGroup/__tests__/ButtonGroup.test.tsx
  main/uis/ButtonGroup/index.tsx
  main/uis/Typography/Typography.tsx
  main/uis/Typography/TypographyInverted.tsx
  package.json
  stories/uis/ButtonGroupStories/ButtonGroupColorStory.tsx
  stories/uis/ButtonGroupStories/common/BasicButton.tsx
  stories/uis/ButtonGroupStories/common/CustomButton.tsx
  stories/uis/ButtonGroupStories/common/CustomData.tsx
  stories/uis/ButtonGroupStories/common/SingleSelect.tsx
  stories/uis/ButtonGroupStories/common/Vertical.tsx
  stories/uis/ButtonGroupStories/index.tsx
  stories/uis/ButtonGroupStories/useButtonGroupKnobs.ts
  yarn.lock
Labels: :construction_worker_man: refactor

#246 apply storybook-dark-mode
  docs/.storybook/darkTheme.js
  docs/.storybook/lightTheme.js
  docs/.storybook/main.js
  docs/.storybook/manager.js
  docs/.storybook/preview.js
  docs/package.json
  docs/src/components/Accordion/Accordion.stories.mdx
  docs/src/components/Accordion/index.tsx
  docs/src/components/Button/AdditionalElement.tsx
  docs/src/components/Button/Basic.tsx
  docs/src/components/Button/Button.stories.mdx
  docs/src/components/Button/Disabled.tsx
  docs/src/components/Button/Link.tsx
  docs/src/components/Button/Loading.tsx
  docs/src/components/Button/OnPress.tsx
  docs/src/components/Button/Outlined.tsx
  docs/src/components/Button/Sizes.tsx
  docs/src/components/Button/Solid.tsx
  docs/src/components/Button/index.tsx
  docs/src/components/ButtonGroup/ButtonGroup.stories.mdx
  docs/src/components/ButtonGroup/index.tsx
  docs/src/components/Checkbox/Basic.tsx
  docs/src/components/Checkbox/Checkbox.stories.mdx
  docs/src/components/Checkbox/Disabled.tsx
  docs/src/components/Checkbox/EndElement.tsx
  docs/src/components/Checkbox/Solid.tsx
  docs/src/components/Checkbox/StartElement.tsx
  docs/src/components/Checkbox/index.tsx
  docs/src/components/EditText/EditText.stories.mdx
  docs/src/components/FAB/FAB.stories.mdx
  docs/src/components/FAB/index.tsx
  docs/src/components/Icon/Default.tsx
  docs/src/components/Icon/Icon.stories.mdx
  docs/src/components/Icon/index.tsx
  docs/src/components/IconButton/IconButton.stories.mdx
  docs/src/components/IconButton/index.tsx
  docs/src/components/LoadingIndicator/Basic.tsx
  docs/src/components/LoadingIndicator/ImageVersion.tsx
  docs/src/components/LoadingIndicator/LoadingIndicator.stories.mdx
  docs/src/components/LoadingIndicator/index.tsx
  docs/src/components/ProgressBar/ProgressBar.stories.mdx
  docs/src/components/ProgressBar/index.tsx
  docs/src/components/ProgressCircle/Progress.stories.mdx
  docs/src/components/ProgressCircle/index.tsx
  docs/src/components/RadioGroup/Basic.tsx
  docs/src/components/RadioGroup/Colored.tsx
  docs/src/components/RadioGroup/RadioGroup.stories.mdx
  docs/src/components/RadioGroup/SelectValue.tsx
  docs/src/components/RadioGroup/WithLabels.tsx
  docs/src/components/RadioGroup/WithTitle.tsx
  docs/src/components/RadioGroup/index.tsx
  docs/src/components/SwitchToggle/SwitchToggle.stories.mdx
  docs/src/components/SwitchToggle/index.tsx
  docs/src/contributing/contributing.stories.mdx
  docs/src/overview/readme.stories.mdx
  docs/src/overview/theming.stories.mdx
  docs/yarn.lock
Labels: 📖 documentation, :construction_worker_man: refactor

#247 refactor duplicate code in docs
  docs/.storybook/darkTheme.js
  docs/.storybook/preview.js
  docs/src/components/Button/Button.stories.mdx
  docs/src/components/Button/Outlined.tsx
  docs/src/components/Button/Sizes.tsx
  docs/src/components/Button/Solid.tsx
  docs/src/components/Checkbox/Checkbox.stories.mdx
  docs/src/components/Checkbox/EndElement.tsx
  docs/src/components/Checkbox/StartElement.tsx
  docs/src/components/RadioGroup/Basic.tsx
  docs/src/components/RadioGroup/Colored.tsx
  docs/src/components/RadioGroup/RadioGroup.stories.mdx
  docs/src/components/RadioGroup/SelectValue.tsx
  docs/src/components/RadioGroup/WithLabels.tsx
  docs/src/components/RadioGroup/WithTitle.tsx
  main/uis/RadioGroup/RadioButton.tsx
  main/uis/RadioGroup/index.tsx
  stories/uis/RadioGroupStories/RadioGroupBasicStory.tsx
  stories/uis/RadioGroupStories/RadioGroupElementStory.tsx
Labels: 📖 documentation

#252 feat(enh): typeguard cloned elements to remove warnings
  main/uis/Button/index.tsx
  main/uis/EditText/index.tsx
  main/uis/FAB/__tests__/FAB.test.tsx
  main/uis/Hr/index.tsx
  main/uis/IconButton/index.tsx
  main/uis/ProgressBar/index.tsx
  main/uis/Styled/StyledComponents.tsx
  main/uis/Typography/Typography.tsx
  main/uis/Typography/TypographyInverted.tsx
  main/utils/guards.ts
  main/utils/utils.ts
Labels: 🎯 feature

#253 feat: start and end elements on [EditText]
  .gitignore
  .storybook/main.js
  .storybook/preview.js
  App.tsx
  __mocks__/@expo/match-media.ts
  main/uis/EditText/__tests__/EditText.test.tsx
  main/uis/EditText/index.tsx
  main/utils/guards.ts
  packages/__tests__/CalendarCarousel.test.tsx
  packages/theme/ThemeProvider.tsx
  packages/theme/package.json
  stories/uis/Button.stories.tsx
  stories/uis/EditText.stories.tsx
  stories/uis/EditTextStories/EditTextStartEndStory.tsx
  stories/uis/EditTextStories/index.tsx
  storybook/addons.js
Labels: 🎯 feature
